### PR TITLE
RF Work + Kendall & Pearson correlation

### PR DESCRIPTION
**Pull request by cwali09**
Added some work for identifying important features with the random forest, also did kendall and pearson correlation per discrete and continuous features.

Added some more visualization tools, added some more questions to answer based off the important features found via random forest

### CODE REVIEW

**Comment by S-Bryce** [comment]
Hey, thanks for all of the work on this - could you enable reviewNB on this repo so that I can add some review comments? Trying to add review comments and code suggestions on the raw notebook in GitHub is agonizing

**Review by S-Bryce — CHANGES_REQUESTED** [review]
Good stuff! Most of the comments are stuff to do with the figures to try and ease the headache of any future merge conflicts - otherwise, just a few comments where I happened to notice something I had a question about

**Comment by cwali09** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617338'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>strange, this isn't in my branch anymore as I previously removed this. not sure why it's showing up here</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617358'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617367'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>removed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617371'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>reparsed and fixed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617376'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617341'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617345'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617368'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617390'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617401'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617404'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617406'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617410'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>fixed</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617415'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>removed, error is fixed in your branch</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617380'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617384'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617396'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>-- write passage about useful data found by rfr and correlation matrices --</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617353'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617348'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by cwali09** [comment]
<p>--todo--</p>

---

 <a href='https://app.reviewnb.com/cwali09/ML-Lab-1/pull/4/discussion/#comment-1426617363'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by S-Bryce — APPROVED** [review]
LGTM

**Pull request merged**
